pipeline {
    agent {
        docker {
            image 'python:2.7'
            args ' --user root'
        }
    }

    stages {
        stage('build') {
            when {
                changeset "**/vote/**"
            }
            steps {
                echo "installing requirements"
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                }
            }
        }
        stage('test') {
            when {
                changeset "**/vote/**"
            }
            steps {
                echo "run test ok"
                dir('vote'){
                    sh 'nosetest -v'
                }
            }
        }
    }
    post {
        always {
            echo "is completed"
        }
        failure {
            echo "fail"
        }
        success {
            echo "ok"
        }
    }

}
