pipeline {
    agent any
    stages {
        stage('build') {
            agent {
                docker {
                    image 'python:2.7.16-slim'
                    args ' --user root'
                }
            }

            when {
                changeset "**/vote/**"
            }
            steps {
                echo "installing requirements"
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                }
            }
        }
        stage('test') {
            agent {
                docker {
                    image 'python:2.7.16-slim'
                    args ' --user root'
                }
            }
            when {
                changeset "**/vote/**"
            }
            steps {
                echo "run test ok"
                dir('vote'){
                    sh 'nosetests -v'
                }
            }
        }
        stage('package-image'){
            agent any
            when {
                changeset "**/vote/**"
                branch "master"
            }
            steps {
                echo "preate to package stage"
                script {
                    docker.withRegistry('https://index.docker.io/v1','dcoker-hub-credentials'){
                        def myimage = docker.bild("wilmanpabel/docker-vote-app-test:v${env.BUILD_ID}","./vote")
                        myimage .push()
                        //image.push("${env.BRANCH_NAME}")
                    }
                }
            }

        }
    }
    post {
        always {
            echo "is completed"
        }
        failure {
            echo "fail"
        }
        success {
            echo "ok"
        }
    }

}
